name: Deploy PHP App to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        printf "%s\n" "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 13.233.146.54 >> ~/.ssh/known_hosts

    - name: Test SSH connection
      run: ssh -o StrictHostKeyChecking=no ubuntu@13.233.146.54 "echo ✅ Connected from GitHub Actions!"

    - name: Deploy code to EC2
      run: scp -r * ubuntu@13.233.146.54:/var/www/html
